travis:
  secure:
    BINSTAR_TOKEN: goddLyP017ThYMVh23k6+dDT6WypTQQb99LYcwWafMcQI5ERnB6OkERQMXUJ+JWVKQI1YoLCdgpLApNnWfK3qdpqxbUFLZgFUvlz9uJrDt45QxlS8y2uDIYoOL++ZM0TWnYhlfcbYMk7Zbl9u9pqPUuzo2VPjg8Z/+X+StaW+GQ3qEUT57pNeK1iVERarKnK6w4I+lMMPINzZvfwSEVYR78ln1X+l3TcLvSvBtrsObSdkHg06yZk8DiLcZcQIH5HtFODE1lXN3UChEKNZ/Bb8yPKEAlTGqjRhyRQBHErvBQ97e2bdx9F70csyuwEgT0xhi/z7v4sLVcTc811TVOgj36rumnXLj78RInjjI9MtQYaV3NJHyK/MLUW5xka1w3XpjCyoc3goFM2b3FPpzW74/HcAQseCFcSUmmzjXBkdqGQILrTIGnAOO5xIVEcZZUpV3NBLYD337nlIaHRthTKOoFf7xw3PJtUw422ThriLZzHbfcocvjqhWu3r0scqmTdgRkO4HkYY/j6/S/HqOdX77jS4eVUF7qvjU6e6/3SbwytJvXuYFLyOjME4j+bxpkvMhkyHeL660zcS+FtFyiAUfycdl1XJ4IZ73zDgeSaF8dVhWz9haRKLxd8FBfpwbDOqq2JDD432nNG6+szg8DJwIyoMtN3KepHd+tQjofFE0I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
